ALTER TABLE WF_JOBS DROP PARENTID;
ALTER TABLE WF_JOBS ADD PARENT_ID VARCHAR2(255);
ALTER TABLE WF_ACTIONS MODIFY EXECUTION_PATH VARCHAR2(1024);
ALTER TABLE COORD_JOBS ADD DONE_MATERIALIZATION NUMBER DEFAULT 0;
ALTER TABLE COORD_JOBS ADD APP_NAMESPACE VARCHAR2(255);