# please replace "OOZIEDB" to your schema name

UPDATE OOZIEDB.COORD_JOBS
SET STATUS = 'RUNNING',PENDING = 1
WHERE ID IN 
(
SELECT JOB_ID FROM COORD_ACTIONS WHERE JOB_ID IN (
SELECT ID FROM COORD_JOBS WHERE STATUS = 'SUCCEEDED') AND  (STATUS != 'FAILED' AND
STATUS != 'SUCCEEDED' AND STATUS != 'KILLED' AND STATUS != 'TIMEDOUT') 
);

UPDATE OOZIEDB.COORD_JOBS SET STATUS = 'RUNNING' WHERE STATUS = 'PREMATER';

UPDATE OOZIEDB.COORD_ACTIONS 
SET STATUS = 'SUSPENDED'
WHERE ID IN(
SELECT A.ID FROM COORD_ACTIONS A, WF_JOBS B WHERE A.EXTERNAL_ID = B.ID
AND B.STATUS = 'SUSPENDED' AND A.STATUS = 'RUNNING'
);
